### ISSUE TITLE
Initialize Dex issue

### ISSUE THREAD

**Issue by rosemerel** [adaltas/ece-webtech-2021-fall#24]
I've downloaded the project folder and started initialize it. 

Install Go
_apt install golang-go_
Download Dex
_git clone https://github.com/dexidp/dex.git_
Build Dex
_cd dex_
=> done successfully 

But the "_make_" command gave me this error:

-mod=mod not supported (can be '', 'readonly', or 'vendor')
storage/ent/generate.go:3: running "go": exit status 1
make: *** [Makefile:34 : generate] Erreur 1

**Comment by wdavidw** [comment]
What is your environment, from the `apt` command, I guess ubuntu, but which version and is it inside a virtualbox ?

**Comment by wdavidw** [comment]
Did you followed the instructions: https://dexidp.io/docs/getting-started/
From what you wrote, it does look like.

**Comment by rosemerel** [comment]
I followed the instructions but the `make` command gave me an error so I can't go on. Everything worked fine when I used dex for TP6. 
And I'm working on` Ubuntu 20.04.3 LTS` (dualboot)

**Comment by mattAmiral** [comment]
I had the same issue with the same ubuntu version. The problem was fixed with downloading the latest version of golang from their official website : https://golang.org/

Check your golang version : go version 
And check it is the latest version. 
If not then uninstall your current go with : sudo apt-get purge golang*

If this command does not work check this page : https://askubuntu.com/questions/742078/uninstalling-go-golang

And then download golang from their official website (instructions are given their)

**Comment by rosemerel** [comment]
Yes it worked. I've deleted go from my computer then re installed it with this tutorial https://www.youtube.com/watch?v=4zVJBltNwD0 (replacing  version 1.14.7 with 1.17.3).
Thank you :)

**Comment by wdavidw** [comment]
It was `make install` and not `make`.
