### ISSUE TITLE
Date of messages

### ISSUE THREAD

**Issue by Sheixxx** [adaltas/ece-webtech-2021-fall#39]
Hello,

I have a problem with the date of the messages.
They change all the time and I can't understand why.

Can you please help me?

I attach a screenshot as an example
![Capture](https://user-images.githubusercontent.com/46935021/146039096-be69955b-22e3-4461-9939-fe8b5e53fbc0.PNG)

**Comment by Sheixxx** [comment]
The code of the messages has not been modified (version given in the git)
![Capture](https://user-images.githubusercontent.com/46935021/146039674-1bdd3091-e1a5-45dc-9e79-f1633f2e7d8c.PNG)

**Comment by clementbouvard** [comment]
Hello,
You need to divide the value of message.creation by 1000 because it is in microseconds instead of milliseconds. dayjs or luxon only understand milliseconds, otherwise they put the maximum date, they think you are in the future.

I hope this helped you

**Comment by kellianoy** [comment]
In fact, there is a problem located inside of the basic project code. 

The `dayjs().calendar(message.creation)` doesn't work, because it is not suited for it. You have to find a way to change the unix timestamp given by microtime in the db into a properly readable time object with the good representation you want to find.

You can take a look at:

Dayjs format: https://day.js.org/docs/en/display/format for more informations.
Date object in js: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date

Best of luck for the rest of your project.

**Comment by Sheixxx** [comment]
Thanks for the answers, I will look into it

**Comment by kellianoy** [comment]
It really shouldn't change @Sheixxx. 

You are getting this value from your database, and it is a fixed attribute that corresponds to the id of a message. The value should really be fixed. 

Please check if you are getting the right attribute from your database. If so, please check that your message list contains the right elements.
