### ISSUE TITLE
Tokens not working, probably a dex issue.

### ISSUE THREAD

**Issue by AntoineBenar** [adaltas/ece-webtech-2021-fall#40]
I have a problem : once I logged with oauth2, I face this page : 
![crash web 1](https://user-images.githubusercontent.com/73337708/146237170-aee1f88c-ee3c-43bc-97c9-316cbd5e2794.png)
The rest of the error : 
![image](https://user-images.githubusercontent.com/73337708/146238054-3ceced71-3006-46ee-acd1-f656cafb36ef.png)

And if I click on "welcome", it logs me out and I am on this page : 
![image](https://user-images.githubusercontent.com/73337708/146237314-7ff93940-903e-4f94-9fdc-682353fc1f75.png)
To run servers I do those commands : 
![image](https://user-images.githubusercontent.com/73337708/146237570-f51473e4-c091-4a5a-8cb0-df128bb088cd.png)
![image](https://user-images.githubusercontent.com/73337708/146237618-f6b3164a-825b-4a8a-ad15-18b119f285cb.png)
![image](https://user-images.githubusercontent.com/73337708/146237739-9c232898-e3c0-4410-b702-538670c4f142.png)

From the begining, I have this error, and I tried everything I found on internet.

This is the Git : https://github.com/AntoineBenar/WebTech_AntoineBenar_AnaisLefebvre/tree/master

Thank you a lot

**Comment by kellianoy** [comment]
First things first : We cannot check your git repository as it is private. 

Seconds : The problem is not where you think it is. Your problem is that your access_token is `undefined`, meaning that you can't authenticate with **undefined**.  

How to solve this ?

I would advise you to check your data at the end of the oauth process, presumably when the user grants the access to the app. This will give you a good idea if the oauth process was succesfully completed. 

If it isn't the case, then it means that you might have a problem either with the codes you gave to the dex config. I'm thinking about two things that needs to be parametered, and if you just pulled the code from the repository, you might not have modified them : 

It is located in connectors, type : github.

1. **Client ID**
2.  **Client Secret**

If you don't remember the oauth process, check out this link : https://www.adaltas.com/fr/2020/11/20/oauth-microservices-public-app/

(This problem is absolutely not linked with the "defined but never used" elements that are more linked to a proper way of coding. I'm thinking about `eslint` or just a `linter`, preventing you from having unused data.)

Best wishes concerning your project.

**Comment by wdavidw** [comment]
Looking at you screenshot, @kellianoy is right, the problem lies in:

> The problem is not where you think it is. Your problem is that your access_token is undefined, meaning that you can't authenticate with undefined.

**Comment by AntoineBenar** [comment]
Thank you for your feedbacks.
My client's id and client secret are well configured in my dex-config/config.yaml, that is the first thing I did, and i just verified it now just to be sure.
Otherwise, i didn't alter any part of the code concerning the back-end, so I don't understand why this error has occured. 

PS : I just sent an invitation to both of you in case you wont to see the source code by yourself.

**Comment by EliottElek** [comment]
What's the URL on this page ? 
<img width="749" alt="image" src="https://user-images.githubusercontent.com/64375473/146520763-85d95e4d-2f76-40e7-8fd2-8c0a2d6d3c56.png">
Is it localhost:3000 or something like localhost:3000/login ?

**Comment by AntoineBenar** [comment]
It is just    " http://127.0.0.1:3000/ " (same as localhost:3000)

**Comment by AntoineBenar** [comment]
This is localhost:3000/login : 

![image](https://user-images.githubusercontent.com/73337708/146524593-fc6cb8e7-1e59-4e87-9606-0a315b316c8f.png)

**Comment by AntoineBenar** [comment]
And with the console : 

![image](https://user-images.githubusercontent.com/73337708/146526008-1895bfbd-feb9-45d3-9dbf-db50e04c88c6.png)

**Comment by EliottElek** [comment]
Did you use the `config.yaml` file from `/dex-config/config.yaml` ?
Seems like your requests to Dex are blocked by cors.

Can you make sure that you have the following lines in your `config.yaml` file :
![image](https://user-images.githubusercontent.com/64375473/146526811-1123228e-2b4a-4a54-a6bf-27587d78c644.png)

**Comment by AntoineBenar** [comment]
The allowedOrigins line were missing, i just added it but unfortunatly the problem is exactly the same as before.

**Comment by EliottElek** [comment]
And you properly restarted your Dex server after changes ?

**Comment by AntoineBenar** [comment]
Silly me! Thank you a lot, now it works! 
The problem was indeed the lack of this code line : allowedOrigins: ['*'] 
I am going to help the other students who have the same problem (all of them I think haha)

Once again, thanks!
